(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))

(require 'init-common)
(require 'init-packages)
(require 'init-basic)
(require 'init-appearance)
(require 'init-config)
(require 'init-flycheck)
(require 'init-lsp)
(require 'init-company)
(require 'init-ccls)
;;(require 'init-irony)
(require 'init-autopair)
(require 'init-multi-cursor)
(require 'init-yasnippet)
(require 'init-python)
(require 'init-dev-common)

(require 'init-ivy)
(require 'init-project)

(require 'init-grep)
(require 'init-markdown)

(require 'init-misc)
